package to.zettagames.crossfire.emulator.game.item;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;

@Getter
@AllArgsConstructor
public enum Items {

    UNKNOWN((byte) -1, "Unknown", ItemType.UNKNOWN),
    BL_LOGO((byte) 20, "BL Logo", ItemType.ITEM),
    GR_LOGO((byte) 21, "GR Logo", ItemType.ITEM),
    CROSSFIRE_LOGO((byte) 22, "CrossFire Logo", ItemType.ITEM),
    CHANNEL_MEGAPHONE((byte) 23, "Channel Megaphone", ItemType.ITEM),
    SERVER_MEGAPHONE((byte) 24, "Server Megaphone", ItemType.ITEM),
    BL_SIGN((byte) 25, "BL Sign", ItemType.ITEM),
    GR_SIGN((byte) 26, "GR Sign", ItemType.ITEM),
    BL_CROUCH((byte) 27, "BL Crouch", ItemType.ITEM),
    GR_CROUCH((byte) 28, "GR Crouch", ItemType.ITEM),
    C4((byte) 29, "C4", ItemType.ITEM),
    BLACKLIST((byte) 30, "BlackList", ItemType.ITEM),
    GLOBALRISK((byte) 31, "GlobalRisk", ItemType.ITEM),
    VOLCANO((byte) 32, "Volcano", ItemType.ITEM),
    HOT_BLOODED_MERCY((byte) 33, "Hot Blooded Mercy", ItemType.ITEM),
    RP_CAPSULE_ULP((byte) 34, "ULP RP Capsule", ItemType.ITEM),
    BULLETPROOF_VEST((byte) 35, "Bulletproof Vest", ItemType.ITEM),
    BULLETPROOF_HELMET((byte) 36, "Bulletproof Helmet", ItemType.ITEM),
    MUZZLE_FLASH_BLUE((byte) 37, "Blue Muzzle Flash", ItemType.ITEM),
    EXTRA_GRENADES((byte) 38, "Extra Grenades", ItemType.ITEM),
    C4_KIT((byte) 39, "C4 Kit", ItemType.ITEM),
    JUMP_BOOTS((byte) 40, "Jump Boots", ItemType.ITEM),
    MUTANT_HOOK((byte) 41, "Mutant Hook", ItemType.ITEM),
    MUTATION_MODE_MAGAZINE((byte) 42, "Mutation Mode Mag", ItemType.ITEM),
    MUTATION_FIRE_SUIT((byte) 43, "Mutant Fire Suit", ItemType.ITEM),
    MUTATION_REDUCE_STUN_AND_KNOCKBACK((byte) 44, "Reduce Stun And Knockback", ItemType.ITEM),
    MUTATION_MUTANT_HULK((byte) 45, "Mutant Hulk", ItemType.ITEM),
    MUTATION_MUTANT_CRAZY((byte) 46, "Crazy Mutant", ItemType.ITEM),
    MUTATION_MUTANT_INK((byte) 47, "Ink Mutant", ItemType.ITEM),
    HEADSHOT((byte) 48, "Headshot", ItemType.ITEM),
    MULTIKILL((byte) 49, "MultiKill", ItemType.ITEM),
    BUBBLE((byte) 50, "Bubble", ItemType.ITEM),
    BUBBLE_2((byte) 51, "Bubble 2", ItemType.ITEM),
    CIRCLE((byte) 52, "Circle", ItemType.ITEM),
    CAPSULE_COUPON((byte) 53, "Capsule Coupon", ItemType.ITEM),
    SNIPER((byte) 54, "Sniper", ItemType.ITEM),
    STORMER((byte) 55, "Stormer", ItemType.ITEM),
    SCOUT((byte) 56, "Scout", ItemType.ITEM),
    SPECIAL_OPS((byte) 57, "Special Ops", ItemType.ITEM),
    FOUNDER((byte) 58, "Founder", ItemType.ITEM),
    FRONTIER((byte) 59, "Frontier", ItemType.ITEM),
    EXP_PLUS_50((byte) 5, "Exp Plus 50", ItemType.ITEM),
    RP_CAPSULE_HALLOWEEN_2011((byte) 60, "2011 Halloween RP Capsule", ItemType.ITEM),
    GR_FIRE((byte) 61, "GR Fire", ItemType.ITEM),
    BL_FIRE((byte) 62, "BL Fire", ItemType.ITEM),
    RP_CAPSULE_CHRISTMAS_2011((byte) 63, "2011 Christmas RP Capsule", ItemType.ITEM),
    RP_CAPSULE_FOX_HOWL((byte) 64, "Fox Howl RP Capsule", ItemType.ITEM),
    MUTATION_MUTANT_ASSASSIN((byte) 69, "Mutant Assassin", ItemType.ITEM),
    HOLLY_GREEN((byte) 70, "Holly Green", ItemType.ITEM),
    RED_RIBBON((byte) 71, "Red Ribbon", ItemType.ITEM),
    SILENT_SNOWMAN((byte) 72, "Silent Snowman", ItemType.ITEM),
    MERRY_SNOWMAN((byte) 73, "Merry Snowman", ItemType.ITEM),
    KILLER_SNOWMAN((byte) 74, "Killer Snowman", ItemType.ITEM),
    CHRISTMAS_TREE((byte) 75, "Christmas Tree", ItemType.ITEM),
    HOLLY_GREEN_2((byte) 76, "Holly Green 2", ItemType.ITEM),
    RED_RIBBON_2((byte) 77, "Red Ribbon 2", ItemType.ITEM),
    NEW_YEAR_2012((byte) 78, "2012 New year", ItemType.ITEM),
    NAME_BANNER_ALBANIA((byte) 79, "Albania", ItemType.ITEM),
    NAME_BANNER_ANDORRA((byte) 80, "Andorra", ItemType.ITEM),
    NAME_BANNER_AUSTRIA((byte) 81, "Austria", ItemType.ITEM),
    NAME_BANNER_BELGIUM((byte) 82, "Belgium", ItemType.ITEM),
    NAME_BANNER_BOSNIAANDHERZEGOvina((byte) 83, "BosniaAndHerzegovina", ItemType.ITEM),
    NAME_BANNER_BULGARIA((byte) 84, "Bulgaria", ItemType.ITEM),
    NAME_BANNER_CROATIA((byte) 85, "Croatia", ItemType.ITEM),
    NAME_BANNER_CZECHREPUBLIC((byte) 86, "CzechRepublic", ItemType.ITEM),
    NAME_BANNER_DENMARK((byte) 87, "Denmark", ItemType.ITEM),
    NAME_BANNER_EUROPEANUNION((byte) 88, "EuropeanUnion", ItemType.ITEM),
    NAME_BANNER_FINLAND((byte) 89, "Finland", ItemType.ITEM),
    NAME_BANNER_GREECE((byte) 90, "Greece", ItemType.ITEM),
    NAME_BANNER_HUNGARY((byte) 91, "Hungary", ItemType.ITEM),
    NAME_BANNER_ICELAND((byte) 92, "Iceland", ItemType.ITEM),
    NAME_BANNER_IRELAND((byte) 93, "Ireland", ItemType.ITEM),
    NAME_BANNER_LUXEMBOURG((byte) 94, "Luxembourg", ItemType.ITEM),
    NAME_BANNER_MACEDONIA((byte) 95, "Macedonia", ItemType.ITEM),
    NAME_BANNER_MALTA((byte) 96, "Malta", ItemType.ITEM),
    NAME_BANNER_MONACO((byte) 97, "Monaco", ItemType.ITEM),
    NAME_BANNER_MONTENEGRO((byte) 98, "Montenegro", ItemType.ITEM),
    NAME_BANNER_NORWAY((byte) 99, "Norway", ItemType.ITEM),
    NAME_BANNER_POLAND((byte) 100, "Poland", ItemType.ITEM),
    NAME_BANNER_ROMANIA((byte) 101, "Romania", ItemType.ITEM),
    NAME_BANNER_SANMARINO((byte) 102, "SanMarino", ItemType.ITEM),
    NAME_BANNER_SERBIA((byte) 103, "Serbia", ItemType.ITEM),
    NAME_BANNER_SLOVAKIA((byte) 104, "Slovakia", ItemType.ITEM),
    NAME_BANNER_SLOVENIA((byte) 105, "Slovenia", ItemType.ITEM),
    NAME_BANNER_SWAZILAND((byte) 106, "Swaziland", ItemType.ITEM),
    NAME_BANNER_SWEDEN((byte) 107, "Sweden", ItemType.ITEM),
    NAME_BANNER_VATICANCITY((byte) 108, "VaticanCity", ItemType.ITEM),
    NAME_BANNER_ARGENTINA((byte) 109, "Argentina", ItemType.ITEM),
    NAME_BANNER_SPAIN((byte) 110, "Spain", ItemType.ITEM),
    NAME_BANNER_NETHERLANDS((byte) 111, "Netherlands", ItemType.ITEM),
    NAME_BANNER_GERMANY((byte) 112, "Germany", ItemType.ITEM),
    NAME_BANNER_ITALY((byte) 113, "Italy", ItemType.ITEM),
    NAME_BANNER_BRAZIL((byte) 114, "Brazil", ItemType.ITEM),
    NAME_BANNER_FRANCE((byte) 115, "France", ItemType.ITEM),
    NAME_BANNER_PORTUGAL((byte) 116, "Portugal", ItemType.ITEM),
    NAME_BANNER_SOUTHAFRICA((byte) 117, "SouthAfrica", ItemType.ITEM),
    NAME_BANNER_ENGLAND((byte) 118, "England", ItemType.ITEM),
    NAME_BANNER_SOUTHKOREA((byte) 119, "SouthKorea", ItemType.ITEM),
    NAME_BANNER_USA((byte) 120, "Usa", ItemType.ITEM),
    NAME_BANNER_JAPAN((byte) 121, "Japan", ItemType.ITEM),
    NAME_BANNER_VIETNAM((byte) 122, "Vietnam", ItemType.ITEM),
    ZOMBIE_BOX_CRYSTAL((byte) 123, "Crystal Box", ItemType.ITEM),
    ZOMBIE_BOX_GOLD((byte) 124, "Gold Box", ItemType.ITEM),
    ZOMBIE_BOX_SILVER((byte) 125, "Silver Box", ItemType.ITEM),
    ZOMBIE_BOX_BRONZE((byte) 126, "Bronze Box", ItemType.ITEM),
    MUZZLE_FLASH_GREEN((byte) 127, "Green Muzzle Flash", ItemType.ITEM),
    SWARM((byte) 128, "Swarm", ItemType.ITEM),
    INFECTED((byte) 129, "Infected", ItemType.ITEM),
    QUARANTINE((byte) 130, "Quarantine", ItemType.ITEM),
    OUTBREAK((byte) 131, "Outbreak", ItemType.ITEM),
    ZOMBIE_BOX_BOSS_HERACLOPS((byte) 132, "Heraclops Box", ItemType.ITEM),
    ZOMBIE_BOX_BOSS_CHAOS((byte) 133, "Chaos Box", ItemType.ITEM),
    ZOMBIE_HYPO_MEDIC_GUN_SMALL((byte) 134, "Hypo Med Gun S", ItemType.ITEM),
    ZOMBIE_HYPO_MEDIC_GUN_LARGE((byte) 135, "Hypo Med Gun L", ItemType.ITEM),
    ZOMBIE_RESPAWN_TOKEN((byte) 136, "Respawn Token", ItemType.ITEM),
    RP_CAPSULE_M14EBR((byte) 137, "M14EBR RP Capsule", ItemType.ITEM),
    RP_CAPSULE_RPK_GOLD((byte) 138, "RPK Gold RP Capsule", ItemType.ITEM),
    RP_CAPSULE_MOS((byte) 139, "MOS RP Capsule", ItemType.ITEM),
    HERACLOPS((byte) 140, "Heraclops", ItemType.ITEM),
    GHOST((byte) 141, "Ghost", ItemType.ITEM),
    FLAME((byte) 142, "Flame", ItemType.ITEM),
    BOSS_CHAOS((byte) 143, "Boss Chaos", ItemType.ITEM),
    BOSS_CHAOS_2((byte) 144, "Boss Chaos 2", ItemType.ITEM),
    BOSS_HERACLOPS((byte) 145, "Boss Heraclops", ItemType.ITEM),
    BOSS_HERACLOPS_2((byte) 146, "Boss Heraclops 2", ItemType.ITEM),
    RP_CAPSULE_M4A1_CUSTOM((byte) 147, "M4A1 Custom RP Capsule", ItemType.ITEM),
    RP_CAPSULE_M37_STAKEOUT((byte) 148, "M37 Stakeout RP Capsule", ItemType.ITEM),
    RP_CAPSULE_ULP_X((byte) 149, "ULP X RP Capsule", ItemType.ITEM),
    A_POINT((byte) 150, "A Point", ItemType.ITEM),
    B_POINT((byte) 151, "B Point", ItemType.ITEM),
    SNOWFLAKE_FOREST((byte) 152, "Snowflake Forest", ItemType.ITEM),
    GREEN_DOTS((byte) 153, "Green Dots", ItemType.ITEM),
    FUNCTION_SMOKE_REDUCE((byte) 154, "Function Smoke Reduce", ItemType.ITEM),
    RP_CAPSULE_DSR_1_DIGITAL_CAMO((byte) 155, "DSR-1 DC RP Capsule", ItemType.ITEM),
    RP_CAPSULE_SCAR_HEAVY_CAMO((byte) 156, "Scar Heavy Camo RP Capsule", ItemType.ITEM),
    COLOR_CALLSIGN((byte) 157, "Color Callsign", ItemType.ITEM),
    COLOR_CHATTING((byte) 158, "ColorChatting", ItemType.ITEM),
    RP_CAPSULE_GATLING_GUN_GOLD((byte) 159, "Gatling Gun Gold RP Capsule", ItemType.ITEM),
    RP_CAPSULE_AK47_KNIFE_BLACK_STRIPES((byte) 160, "AK47 Knife BS RP Capsule", ItemType.ITEM),
    RP_CAPSULE_WINCHESTER_GOLD((byte) 161, "Winchester Gold RP Capsule", ItemType.ITEM),
    KNIFE_MASTER((byte) 162, "Knife Master", ItemType.ITEM),
    BLUE_THUNDER((byte) 163, "Blue Thunder", ItemType.ITEM),
    FORCES_COLLIDE((byte) 164, "Forces Collide", ItemType.ITEM),
    RP_CAPSULE_DUAL_COLT_1911S_RED_DRAGON((byte) 165, "Dual 1911s RD RP Capsule", ItemType.ITEM),
    RP_CAPSULE_M4A1_BANDAGE((byte) 166, "M4A1 Bandage RP Capsule", ItemType.ITEM),
    RP_CAPSULE_MEGA_RED_DRAGON((byte) 167, "Red Dragon Mega RP Capsule", ItemType.ITEM),
    PLUS_MISSION((byte) 168, "Plus Mission", ItemType.ITEM),
    BADGE_PLUS_100((byte) 169, "Badge Plus 100", ItemType.ITEM),
    GP_PLUS_70((byte) 170, "GP Plus 70", ItemType.ITEM),
    EXP_PLUS_50_2((byte) 171, "Exp Plus 50 2", ItemType.ITEM),
    RP_CAPSULE_KRISS_SUPER_V_LIQUID_METAL((byte) 172, "Kriss S V LM RP Capsule", ItemType.ITEM),
    RP_CAPSULE_MG3_GOLD((byte) 173, "MG3 Gold RP Capsule", ItemType.ITEM),
    RP_CAPSULE_DSR_1_RUSTY((byte) 174, "DSR-1 Rusty RP Capsule", ItemType.ITEM),
    RP_CAPSULE_GALIL_ARM((byte) 175, "Galil RP Capsule", ItemType.ITEM),
    EXP_PLUS_100((byte) 176, "Exp Plus 100", ItemType.ITEM),
    SUMMER_GAMES_2012_LONDON_1((byte) 177, "London 2012 Summer Games 1", ItemType.ITEM),
    SUMMER_GAMES_2012_LONDON_2((byte) 178, "London 2012 Summer Games 2", ItemType.ITEM),
    SUMMER_GAMES_2012_LONDON_1_2((byte) 179, "London 2012 Summer Games 1 2", ItemType.ITEM),
    SUMMER_GAMES_2012_LONDON_2_2((byte) 180, "London 2012 Summer Games 2 2", ItemType.ITEM),
    RP_CAPSULE_MEGA_1_YEAR_ANNIVERSARY_1((byte) 181, "1 Year Anniversary Mega RP Capsule 1", ItemType.ITEM),
    GP_CAPSULE_MP7A1((byte) 182, "MP7A1 GP Capsule", ItemType.ITEM),
    RP_CAPSULE_GSG_9((byte) 183, "GSG-9 RP Capsule", ItemType.ITEM),
    RP_CAPSULE_MEGA_1_YEAR_ANNIVERSARY_2((byte) 184, "1 Year Anniversary Mega RP Capsule 2", ItemType.ITEM),
    RP_CAPSULE_MEGA_1_YEAR_ANNIVERSARY_3((byte) 185, "1 Year Anniversary Mega RP Capsule 3", ItemType.ITEM),
    RP_CAPSULE_STERLING((byte) 186, "Sterling RP Capsule", ItemType.ITEM),
    RP_CAPSULE_M37_STAKEOUT_HELLFIRE((byte) 187, "M37 Stakeout Hellfire RP Capsule", ItemType.ITEM),
    RP_CAPSULE_SCAR_HEAVY_RED_DRAGON((byte) 188, "Scar Heavy RD RP Capsule", ItemType.ITEM),
    RP_CAPSULE_OCTANE_1((byte) 189, "Octane RP Capsule 1", ItemType.ITEM),
    WCG_2012_1((byte) 190, "2012 WCG 1", ItemType.ITEM),
    WCG_2012_2((byte) 191, "2012 WCG 2", ItemType.ITEM),
    WCG_2012_1_2((byte) 192, "2012 WCG 1 2", ItemType.ITEM),
    WCG_2012_2_2((byte) 193, "2012 WCG 2 2", ItemType.ITEM),
    OCTANE((byte) 194, "Octane", ItemType.ITEM),
    RP_CAPSULE_OCTANE_2((byte) 195, "Octane RP Capsule 2", ItemType.ITEM),
    RP_CAPSULE_AUTUMN_CAMO((byte) 196, "Autumn Camo RP Capsule", ItemType.ITEM),
    RP_CAPSULE_KNUCKLES((byte) 197, "Knuckles RP Capsule", ItemType.ITEM),
    RP_CAPSULE_MEGA_HALLOWEEN_2012_1((byte) 198, "2012 Halloween Mega RP Capsule 1", ItemType.ITEM),
    RP_CAPSULE_MEGA_HALLOWEEN_2012_2((byte) 199, "2012 Halloween Mega RP Capsule 2", ItemType.ITEM),
    FIERY_PUMPKIN((byte) 200, "Fiery Pumpkin", ItemType.ITEM),
    SPOOKY_PUMPKIN((byte) 201, "Spooky Pumpkin", ItemType.ITEM),
    RP_CAPSULE_AK47_SCOPE((byte) 202, "AK47-S RP Capsule", ItemType.ITEM),
    RP_CAPSULE_DESERT_EAGLE_SCOPE((byte) 203, "Desert Eagle S RP Capsule", ItemType.ITEM),
    GP_CAPSULE_XM8_B((byte) 204, "XM8-B GP Capsule", ItemType.ITEM),
    RP_CAPSULE_RPK_RED_EAGLE((byte) 205, "RPK Red Eagle RP Capsule", ItemType.ITEM),
    RP_CAPSULE_MEGA_GOLD_2012((byte) 206, "2012 Gold Mega RP Capsule", ItemType.ITEM),
    RP_CAPSULE_XMAS_2012((byte) 207, "2012 Xmas RP Capsule", ItemType.ITEM),
    XMAS_2012((byte) 208, "2012 Xmas", ItemType.ITEM),
    XMAS_2012_2((byte) 209, "2012 Xmas 2", ItemType.ITEM),
    TREE_XMAS((byte) 210, "Tree Xmas", ItemType.ITEM),
    F_PROTECTION_GOGGLE_GHOST_X((byte) 211, "F Protection Goggle Ghost X", ItemType.ITEM),
    BIOHAZARD_BACKPACK_EXCHANGE_TICKET_FUNCTIONAL((byte) 212, "Biohazard Backpack Exchange Ticket Functional", ItemType.ITEM),
    BIOHAZARD_ACQUISITION_TICKET_1((byte) 213, "Biohazard Acquisition Ticket 1", ItemType.ITEM),
    BIOHAZARD_ACQUISITION_TICKET_2((byte) 214, "Biohazard Acquisition Ticket 2", ItemType.ITEM),
    BIOHAZARD_ACQUISITION_TICKET_3((byte) 215, "Biohazard Acquisition Ticket 3", ItemType.ITEM),
    BIOHAZARD_ACQUISITION_TICKET_4((byte) 216, "Biohazard Acquisition Ticket 4", ItemType.ITEM),
    ZOMBIE_BOX_BOSS_MEGA_WARMONGER((byte) 217, "Mega Warmonger Box", ItemType.ITEM),
    MEGA_WARMONGER((byte) 218, "Mega Warmonger", ItemType.ITEM),
    MEGA_WARMONGER_2((byte) 219, "Mega Warmonger 2", ItemType.ITEM),
    MUZZLE_FLASH_PURPLE((byte) 220, "Purple Muzzle Flash", ItemType.ITEM),
    SITTING_BEHIND_BL_FIRE((byte) 221, "Sitting Behind BL Fire", ItemType.ITEM),
    SITTING_BEHIND_GR_FIRE((byte) 222, "Sitting Behind GR Fire", ItemType.ITEM),
    RP_CAPSULE_NEW_YEAR_2013((byte) 223, "2013 New Year RP Capsule", ItemType.ITEM),
    RP_CAPSULE_THOMPSON_GOLD((byte) 224, "Thompson Gold RP Capsule", ItemType.ITEM),
    RP_CAPSULE_M4A1_ADV_CRYSTAL((byte) 225, "M4A1 A Crystal RP Capsule", ItemType.ITEM);

    private final byte id;
    private final String name;
    private final ItemType type;

    public static Items getItemById(byte id) {
        return Arrays.stream(values()).filter(item -> item.id == id).findFirst().orElse(UNKNOWN);
    }

}
